version: "3.8"

services:
  web:
    image: silaa/grading-web2:latest
    container_name: grading-web
    ports:
      - "8001:8000"
    volumes:
      - ./db.sqlite:/opt/grading/db.sqlite
      - ./logs:/opt/grading/logs
      - /opt/grading:/opt/grading
      - /opt/grading/app:/opt/grading/app
      - /opt/grading/app/schemes:/opt/grading/app/schemes
      - /opt/grading/app/api.py:/opt/grading/app/api.py:ro
      - /var/log/gradingctl:/var/log/gradingctl
    restart: unless-stopped
    environment:
      - GRAFANA_URL=http://100.70.220.18:3001
      - GRAFANA_USER=admin
      - GRAFANA_PASS=29CRk6YAIEnVJPj16dd798IByF06EV5kxo9ljULK
    env_file:
      - .env
    networks:
      - grading-net

  db-admin:
    image: coleifer/sqlite-web
    container_name: grading-db-admin
    restart: unless-stopped
    ports:
      - "8002:8080"
    volumes:
      - ./db.sqlite:/data/db.sqlite
    # Perbaikan: tambahkan 'sqlite_web' sebelum path filenya
    command: sqlite_web /data/db.sqlite -H 0.0.0.0 -p 8080
    networks:
      - grading-net

networks:
  grading-net:
    name: grading-net
